# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd474cf7d3b6c0ccb651cdd2c12181d041864afaf6125573cb6cf561c3f97b557b3635d7fdddbc4620a9f24086170b0e54c481f3a2f1aa64c10dc8b4a1fc19ba

test:
  secret_key_base: ab46393a88aabc470c879c419bc6ea94709ac8cb955506e96e6a8f64f17e950e455f80e8eafd21e93f67ceb9d07aefb80650e93d53bffa8c8dcc639f2d8045ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
